#links = //td//a/@href
#verb = //div[@class="card border-light mb-3"]/h1[@class="card-header special1 heading"]/span/text()
#past =  //div[@class="card border-light mb-3"]/div[@class="card-body"]/div[@class="card-text special"]/div[@class="content"]/span/text()
#infinitive = //table[@class="table table-striped table-bordered tg"]//tr[2]/td[1]//text()
#presentParticiple = //table[@class="table table-striped table-bordered tg"]//tr[2]/td[2]//text()
#pastTense = //table[@class="table table-striped table-bordered tg"]//tr[2]/td[3]//text()
#pastParticiple = //table[@class="table table-striped table-bordered tg"]//tr[2]/td[4]//text()
#conjugation = (//table[@class="table table-striped table-bordered table-light tg"])[1]
#simplePresentConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[1]//tr[2]//text()
#simplePresentConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[1]//tr[3]//text()
#simplePresentConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[1]//tr[4]//text()
#presentContinuousConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[2]//tr[2]//text()
#presentContinuousConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[2]//tr[3]//text()
#presentContinuousConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[2]//tr[4]//text()
#presentPerfectConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[3]//tr[2]//text()
#presentPerfectConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[3]//tr[3]//text()
#presentPerfectConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[3]//tr[4]//text()
#presentPerfectContinuousConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[4]//tr[2]//text()
#presentPerfectContinuousConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[4]//tr[3]//text()
#presentPerfectContinuousConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[4]//tr[4]//text()
#simplePastConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[5]//tr[2]//text()
#simplePastConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[5]//tr[3]//text()
#simplePastConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[5]//tr[4]//text()
#pastContinuousConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[6]//tr[2]//text()
#pastContinuousConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[6]//tr[3]//text()
#pastContinuousConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[6]//tr[4]//text()
#pastPerfectConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[7]//tr[2]//text()
#pastPerfectConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[7]//tr[3]//text()
#pastPerfectConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[7]//tr[4]//text()
#pastPerfectContinuousConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[8]//tr[2]//text()
#pastPerfectContinuousConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[8]//tr[3]//text()
#pastPerfectContinuousConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[8]//tr[4]//text()
#futureConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[9]//tr[2]//text()
#futureConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[9]//tr[3]//text()
#futureConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[9]//tr[4]//text()
#futureContinuousConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[10]//tr[2]//text()
#futureContinuousConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[10]//tr[3]//text()
#futureContinuousConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[10]//tr[4]//text()
#futurePerfectConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[11]//tr[2]//text()
#futurePerfectConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[11]//tr[3]//text()
#futurePerfectConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[11]//tr[4]//text()
#futurePerfectContinuousConjugation1 = (//table[@class="table table-striped table-bordered table-light tg"])[12]//tr[2]//text()
#futurePerfectContinuousConjugation2 = (//table[@class="table table-striped table-bordered table-light tg"])[12]//tr[3]//text()
#futurePerfectContinuousConjugation3 = (//table[@class="table table-striped table-bordered table-light tg"])[12]//tr[4]//text()

import scrapy

# verbsPages = []
# contadorverbos = 1
# while contadorverbos <= 31:
#     verbsPages.append("https://pasttenses.com/irregular-verbs-list/"+str(contadorverbos))
#     print("""'https://pasttenses.com/irregular-verbs-list/"""+str(contadorverbos)+"""',""")
#     contadorverbos += 1

class EnglishSpider(scrapy.Spider):
    name = 'get-words'
    start_urls = [
        'https://pasttenses.com/verbs-list/1',
        'https://pasttenses.com/verbs-list/2',
        'https://pasttenses.com/verbs-list/3',
        'https://pasttenses.com/verbs-list/4',
        'https://pasttenses.com/verbs-list/5',
        'https://pasttenses.com/verbs-list/6',
        'https://pasttenses.com/verbs-list/7',
        'https://pasttenses.com/verbs-list/8',
        'https://pasttenses.com/verbs-list/9',
        'https://pasttenses.com/verbs-list/10',
        'https://pasttenses.com/verbs-list/11',
        'https://pasttenses.com/verbs-list/12',
        'https://pasttenses.com/verbs-list/13',
        'https://pasttenses.com/verbs-list/14',
        'https://pasttenses.com/verbs-list/15',
        'https://pasttenses.com/verbs-list/16',
        'https://pasttenses.com/verbs-list/17',
        'https://pasttenses.com/verbs-list/18',
        'https://pasttenses.com/verbs-list/19',
        'https://pasttenses.com/verbs-list/20',
        'https://pasttenses.com/verbs-list/21',
        'https://pasttenses.com/verbs-list/22',
        'https://pasttenses.com/verbs-list/23',
        'https://pasttenses.com/verbs-list/24',
        'https://pasttenses.com/verbs-list/25',
        'https://pasttenses.com/verbs-list/26',
        'https://pasttenses.com/verbs-list/27',
        'https://pasttenses.com/verbs-list/28',
        'https://pasttenses.com/verbs-list/29',
        'https://pasttenses.com/verbs-list/30',
        'https://pasttenses.com/verbs-list/31',
        'https://pasttenses.com/verbs-list/32',
        'https://pasttenses.com/verbs-list/33',
        'https://pasttenses.com/verbs-list/34',
        'https://pasttenses.com/verbs-list/35',
        'https://pasttenses.com/verbs-list/36',
        'https://pasttenses.com/verbs-list/37',
        'https://pasttenses.com/verbs-list/38',
        'https://pasttenses.com/verbs-list/39',
        'https://pasttenses.com/verbs-list/40',
        'https://pasttenses.com/verbs-list/41',
        'https://pasttenses.com/verbs-list/42',
        'https://pasttenses.com/verbs-list/43',
        'https://pasttenses.com/verbs-list/44',
        'https://pasttenses.com/verbs-list/45',
        'https://pasttenses.com/verbs-list/46',
        'https://pasttenses.com/verbs-list/47',
        'https://pasttenses.com/verbs-list/48',
        'https://pasttenses.com/verbs-list/49',
        'https://pasttenses.com/verbs-list/50',
        'https://pasttenses.com/verbs-list/51',
        'https://pasttenses.com/verbs-list/52',
        'https://pasttenses.com/verbs-list/53',
        'https://pasttenses.com/verbs-list/54',
        'https://pasttenses.com/verbs-list/55',
        'https://pasttenses.com/verbs-list/56',
        'https://pasttenses.com/verbs-list/57',
        'https://pasttenses.com/verbs-list/58',
        'https://pasttenses.com/verbs-list/59',
        'https://pasttenses.com/verbs-list/60',
        'https://pasttenses.com/verbs-list/61',
        'https://pasttenses.com/verbs-list/62',
        'https://pasttenses.com/verbs-list/63',
        'https://pasttenses.com/verbs-list/64',
        'https://pasttenses.com/verbs-list/65',
        'https://pasttenses.com/verbs-list/66',
        'https://pasttenses.com/verbs-list/67',
        'https://pasttenses.com/verbs-list/68',
        'https://pasttenses.com/verbs-list/69',
        'https://pasttenses.com/verbs-list/70',
        'https://pasttenses.com/verbs-list/71',
        'https://pasttenses.com/verbs-list/72',
        'https://pasttenses.com/verbs-list/73',
        'https://pasttenses.com/verbs-list/74',
        'https://pasttenses.com/verbs-list/75',
        'https://pasttenses.com/verbs-list/76',
        'https://pasttenses.com/verbs-list/77',
        'https://pasttenses.com/verbs-list/78',
        'https://pasttenses.com/verbs-list/79',
        'https://pasttenses.com/verbs-list/80',
        'https://pasttenses.com/verbs-list/81',
        'https://pasttenses.com/verbs-list/82',
        'https://pasttenses.com/verbs-list/83',
        'https://pasttenses.com/verbs-list/84',
        'https://pasttenses.com/verbs-list/85',
        'https://pasttenses.com/verbs-list/86',
        'https://pasttenses.com/verbs-list/87',
        'https://pasttenses.com/verbs-list/88',
        'https://pasttenses.com/verbs-list/89',
        'https://pasttenses.com/verbs-list/90',
        'https://pasttenses.com/verbs-list/91',
        'https://pasttenses.com/verbs-list/92',
        'https://pasttenses.com/verbs-list/93',
        'https://pasttenses.com/verbs-list/94',
        'https://pasttenses.com/verbs-list/95',
        'https://pasttenses.com/verbs-list/96',
        'https://pasttenses.com/verbs-list/97',
        'https://pasttenses.com/verbs-list/98',
        'https://pasttenses.com/verbs-list/99',
        'https://pasttenses.com/verbs-list/100',
        'https://pasttenses.com/verbs-list/101',
        'https://pasttenses.com/verbs-list/102',
        'https://pasttenses.com/verbs-list/103',
        'https://pasttenses.com/verbs-list/104',
        'https://pasttenses.com/verbs-list/105',
        'https://pasttenses.com/verbs-list/106',
        'https://pasttenses.com/verbs-list/107',
        'https://pasttenses.com/verbs-list/108',
        'https://pasttenses.com/verbs-list/109',
        'https://pasttenses.com/verbs-list/110',
        'https://pasttenses.com/verbs-list/111',
        'https://pasttenses.com/verbs-list/112',
        'https://pasttenses.com/verbs-list/113',
        'https://pasttenses.com/verbs-list/114',
        'https://pasttenses.com/verbs-list/115',
        'https://pasttenses.com/verbs-list/116',
        'https://pasttenses.com/verbs-list/117',
        'https://pasttenses.com/verbs-list/118',
        'https://pasttenses.com/verbs-list/119',
        'https://pasttenses.com/verbs-list/120',
        'https://pasttenses.com/verbs-list/121',
        'https://pasttenses.com/verbs-list/122',
        'https://pasttenses.com/verbs-list/123',
        'https://pasttenses.com/verbs-list/124',
        'https://pasttenses.com/verbs-list/125',
        'https://pasttenses.com/verbs-list/126',
        'https://pasttenses.com/verbs-list/127',
        'https://pasttenses.com/verbs-list/128',
        'https://pasttenses.com/verbs-list/129',
        'https://pasttenses.com/verbs-list/130',
        'https://pasttenses.com/verbs-list/131',
        'https://pasttenses.com/verbs-list/132',
        'https://pasttenses.com/verbs-list/133',
        'https://pasttenses.com/verbs-list/134',
        'https://pasttenses.com/verbs-list/135',
        'https://pasttenses.com/verbs-list/136',
        'https://pasttenses.com/verbs-list/137',
        'https://pasttenses.com/verbs-list/138',
        'https://pasttenses.com/verbs-list/139',
        'https://pasttenses.com/verbs-list/140',
        'https://pasttenses.com/verbs-list/141',
        'https://pasttenses.com/verbs-list/142',
        'https://pasttenses.com/verbs-list/143',
        'https://pasttenses.com/verbs-list/144',
        'https://pasttenses.com/verbs-list/145',
        'https://pasttenses.com/verbs-list/146',
        'https://pasttenses.com/verbs-list/147',
        'https://pasttenses.com/verbs-list/148',
        'https://pasttenses.com/verbs-list/149',
        'https://pasttenses.com/verbs-list/150',
        'https://pasttenses.com/verbs-list/151',
        'https://pasttenses.com/verbs-list/152',
        'https://pasttenses.com/verbs-list/153',
        'https://pasttenses.com/verbs-list/154',
        'https://pasttenses.com/verbs-list/155',
        'https://pasttenses.com/verbs-list/156',
        'https://pasttenses.com/verbs-list/157',
        'https://pasttenses.com/verbs-list/158',
        'https://pasttenses.com/verbs-list/159',
        'https://pasttenses.com/verbs-list/160',
        'https://pasttenses.com/verbs-list/161',
        'https://pasttenses.com/verbs-list/162',
        'https://pasttenses.com/verbs-list/163',
        'https://pasttenses.com/verbs-list/164',
        'https://pasttenses.com/verbs-list/165',
        'https://pasttenses.com/verbs-list/166',
        'https://pasttenses.com/verbs-list/167',
        'https://pasttenses.com/verbs-list/168',
        'https://pasttenses.com/verbs-list/169',
        'https://pasttenses.com/verbs-list/170',
        'https://pasttenses.com/verbs-list/171',
        'https://pasttenses.com/verbs-list/172',
        'https://pasttenses.com/verbs-list/173',
        'https://pasttenses.com/verbs-list/174',
        'https://pasttenses.com/verbs-list/175',
        'https://pasttenses.com/verbs-list/176',
        'https://pasttenses.com/verbs-list/177',
        'https://pasttenses.com/verbs-list/178',
        'https://pasttenses.com/verbs-list/179',
        'https://pasttenses.com/verbs-list/180',
        'https://pasttenses.com/verbs-list/181',
        'https://pasttenses.com/verbs-list/182',
        'https://pasttenses.com/verbs-list/183',
        'https://pasttenses.com/verbs-list/184',
        'https://pasttenses.com/verbs-list/185',
        'https://pasttenses.com/verbs-list/186',
        'https://pasttenses.com/verbs-list/187',
        'https://pasttenses.com/verbs-list/188',
        'https://pasttenses.com/verbs-list/189',
        'https://pasttenses.com/verbs-list/190',
        'https://pasttenses.com/verbs-list/191',
        'https://pasttenses.com/verbs-list/192',
        'https://pasttenses.com/verbs-list/193',
        'https://pasttenses.com/verbs-list/194',
        'https://pasttenses.com/verbs-list/195',
        'https://pasttenses.com/verbs-list/196',
        'https://pasttenses.com/verbs-list/197',
        'https://pasttenses.com/verbs-list/198',
        'https://pasttenses.com/verbs-list/199',
        'https://pasttenses.com/verbs-list/200',
        'https://pasttenses.com/verbs-list/201',
        'https://pasttenses.com/verbs-list/202',
        'https://pasttenses.com/verbs-list/203',
        'https://pasttenses.com/verbs-list/204',
        'https://pasttenses.com/verbs-list/205',
        'https://pasttenses.com/verbs-list/206',
        'https://pasttenses.com/verbs-list/207',
        'https://pasttenses.com/verbs-list/208',
        'https://pasttenses.com/verbs-list/209',
        'https://pasttenses.com/verbs-list/210',
        'https://pasttenses.com/verbs-list/211',
        'https://pasttenses.com/verbs-list/212',
        'https://pasttenses.com/verbs-list/213',
        'https://pasttenses.com/verbs-list/214',
        'https://pasttenses.com/verbs-list/215',
        'https://pasttenses.com/verbs-list/216',
        'https://pasttenses.com/verbs-list/217',
        'https://pasttenses.com/verbs-list/218',
        'https://pasttenses.com/verbs-list/219',
        'https://pasttenses.com/verbs-list/220',
        'https://pasttenses.com/verbs-list/221',
        'https://pasttenses.com/verbs-list/222',
        'https://pasttenses.com/verbs-list/223',
        'https://pasttenses.com/verbs-list/224',
        'https://pasttenses.com/verbs-list/225',
        'https://pasttenses.com/verbs-list/226',
        'https://pasttenses.com/verbs-list/227',
        'https://pasttenses.com/verbs-list/228',
        'https://pasttenses.com/verbs-list/229',
        'https://pasttenses.com/verbs-list/230',
        'https://pasttenses.com/verbs-list/231',
        'https://pasttenses.com/verbs-list/232',
        'https://pasttenses.com/verbs-list/233',
        'https://pasttenses.com/verbs-list/234',
        'https://pasttenses.com/verbs-list/235',
        'https://pasttenses.com/verbs-list/236',
        'https://pasttenses.com/verbs-list/237',
        'https://pasttenses.com/verbs-list/238',
        'https://pasttenses.com/verbs-list/239',
        'https://pasttenses.com/verbs-list/240',
        'https://pasttenses.com/verbs-list/241',
        'https://pasttenses.com/verbs-list/242',
        'https://pasttenses.com/verbs-list/243',
        'https://pasttenses.com/verbs-list/244',
        'https://pasttenses.com/verbs-list/245',
        'https://pasttenses.com/verbs-list/246',
        'https://pasttenses.com/verbs-list/247',
        'https://pasttenses.com/verbs-list/248',
        'https://pasttenses.com/verbs-list/249',
        'https://pasttenses.com/verbs-list/250',
        'https://pasttenses.com/verbs-list/251',
        'https://pasttenses.com/verbs-list/252',
        'https://pasttenses.com/verbs-list/253',
        'https://pasttenses.com/verbs-list/254',
        'https://pasttenses.com/verbs-list/255',
        'https://pasttenses.com/verbs-list/256',
        'https://pasttenses.com/verbs-list/257',
        'https://pasttenses.com/verbs-list/258',
        'https://pasttenses.com/verbs-list/259',
        'https://pasttenses.com/verbs-list/260',
        'https://pasttenses.com/verbs-list/261',
        'https://pasttenses.com/verbs-list/262',
        'https://pasttenses.com/verbs-list/263',
        'https://pasttenses.com/verbs-list/264',
        'https://pasttenses.com/verbs-list/265',
        'https://pasttenses.com/verbs-list/266',
        'https://pasttenses.com/verbs-list/267',
        'https://pasttenses.com/verbs-list/268',
        'https://pasttenses.com/verbs-list/269',
        'https://pasttenses.com/verbs-list/270',
        'https://pasttenses.com/verbs-list/271',
        'https://pasttenses.com/verbs-list/272',
        'https://pasttenses.com/verbs-list/273',
        'https://pasttenses.com/verbs-list/274',
        'https://pasttenses.com/verbs-list/275',
        'https://pasttenses.com/verbs-list/276',
        'https://pasttenses.com/verbs-list/277',
        'https://pasttenses.com/verbs-list/278',
        'https://pasttenses.com/verbs-list/279',
        'https://pasttenses.com/verbs-list/280',
        'https://pasttenses.com/verbs-list/281',
        'https://pasttenses.com/verbs-list/282',
        'https://pasttenses.com/verbs-list/283',
        'https://pasttenses.com/verbs-list/284',
        'https://pasttenses.com/verbs-list/285',
        'https://pasttenses.com/verbs-list/286',
        'https://pasttenses.com/verbs-list/287',
        'https://pasttenses.com/verbs-list/288',
        'https://pasttenses.com/verbs-list/289',
        'https://pasttenses.com/verbs-list/290',
        'https://pasttenses.com/verbs-list/291',
        'https://pasttenses.com/verbs-list/292',
        'https://pasttenses.com/verbs-list/293',
        'https://pasttenses.com/verbs-list/294',
        'https://pasttenses.com/verbs-list/295',
        'https://pasttenses.com/verbs-list/296',
        'https://pasttenses.com/verbs-list/297',
        'https://pasttenses.com/verbs-list/298',
        'https://pasttenses.com/verbs-list/299',
        'https://pasttenses.com/verbs-list/300',
        'https://pasttenses.com/verbs-list/301',
        'https://pasttenses.com/verbs-list/302',
        'https://pasttenses.com/verbs-list/303',
        'https://pasttenses.com/verbs-list/304',
        'https://pasttenses.com/verbs-list/305',
        'https://pasttenses.com/verbs-list/306',
        'https://pasttenses.com/verbs-list/307',
        'https://pasttenses.com/verbs-list/308',
        'https://pasttenses.com/verbs-list/309',
        'https://pasttenses.com/verbs-list/310',
        'https://pasttenses.com/verbs-list/311',
        'https://pasttenses.com/verbs-list/312',
        'https://pasttenses.com/verbs-list/313',
        'https://pasttenses.com/verbs-list/314',
        'https://pasttenses.com/verbs-list/315',
        'https://pasttenses.com/verbs-list/316',
        'https://pasttenses.com/verbs-list/317',
        'https://pasttenses.com/verbs-list/318',
        'https://pasttenses.com/verbs-list/319',
        'https://pasttenses.com/verbs-list/320',
        'https://pasttenses.com/verbs-list/321',
        'https://pasttenses.com/verbs-list/322',
        'https://pasttenses.com/verbs-list/323',
        'https://pasttenses.com/verbs-list/324',
        'https://pasttenses.com/verbs-list/325',
        'https://pasttenses.com/verbs-list/326',
        'https://pasttenses.com/verbs-list/327',
        'https://pasttenses.com/verbs-list/328',
        'https://pasttenses.com/verbs-list/329',
        'https://pasttenses.com/verbs-list/330',
        'https://pasttenses.com/verbs-list/331',
        'https://pasttenses.com/verbs-list/332',
        'https://pasttenses.com/verbs-list/333',
        'https://pasttenses.com/verbs-list/334',
        'https://pasttenses.com/verbs-list/335',
        'https://pasttenses.com/verbs-list/336',
        'https://pasttenses.com/verbs-list/337',
        'https://pasttenses.com/verbs-list/338',
        'https://pasttenses.com/verbs-list/339',
        'https://pasttenses.com/verbs-list/340',
        'https://pasttenses.com/verbs-list/341',
        'https://pasttenses.com/verbs-list/342',
        'https://pasttenses.com/verbs-list/343',
        'https://pasttenses.com/verbs-list/344',
        'https://pasttenses.com/verbs-list/345',
        'https://pasttenses.com/verbs-list/346',
        'https://pasttenses.com/verbs-list/347',
        'https://pasttenses.com/verbs-list/348',
        'https://pasttenses.com/verbs-list/349',
        'https://pasttenses.com/verbs-list/350',
        'https://pasttenses.com/verbs-list/351',
        'https://pasttenses.com/verbs-list/352',
        'https://pasttenses.com/verbs-list/353',
        'https://pasttenses.com/verbs-list/354',
        'https://pasttenses.com/verbs-list/355',
        'https://pasttenses.com/verbs-list/356',
        'https://pasttenses.com/verbs-list/357',
        'https://pasttenses.com/verbs-list/358',
        'https://pasttenses.com/verbs-list/359',
        'https://pasttenses.com/verbs-list/360',
        'https://pasttenses.com/verbs-list/361',
        'https://pasttenses.com/verbs-list/362',
        'https://pasttenses.com/verbs-list/363',
        'https://pasttenses.com/verbs-list/364',
        'https://pasttenses.com/verbs-list/365',
        'https://pasttenses.com/verbs-list/366',
        'https://pasttenses.com/verbs-list/367',
        'https://pasttenses.com/verbs-list/368',
        'https://pasttenses.com/verbs-list/369',
        'https://pasttenses.com/verbs-list/370',
        'https://pasttenses.com/verbs-list/371',
        'https://pasttenses.com/verbs-list/372',
        'https://pasttenses.com/verbs-list/373',
        'https://pasttenses.com/verbs-list/374',
        'https://pasttenses.com/verbs-list/375',
        'https://pasttenses.com/verbs-list/376',
        'https://pasttenses.com/verbs-list/377',
        'https://pasttenses.com/verbs-list/378',
        'https://pasttenses.com/verbs-list/379',
        'https://pasttenses.com/verbs-list/380',
        'https://pasttenses.com/verbs-list/381',
        'https://pasttenses.com/verbs-list/382',
        'https://pasttenses.com/verbs-list/383',
        'https://pasttenses.com/verbs-list/384',
        'https://pasttenses.com/verbs-list/385',
        'https://pasttenses.com/verbs-list/386',
        'https://pasttenses.com/verbs-list/387',
        'https://pasttenses.com/verbs-list/388',
        'https://pasttenses.com/verbs-list/389',
        'https://pasttenses.com/verbs-list/390',
        'https://pasttenses.com/verbs-list/391',
        'https://pasttenses.com/verbs-list/392',
        'https://pasttenses.com/verbs-list/393',
        'https://pasttenses.com/verbs-list/394',
        'https://pasttenses.com/verbs-list/395',
        'https://pasttenses.com/verbs-list/396',
        'https://pasttenses.com/verbs-list/397',
        'https://pasttenses.com/verbs-list/398',
        'https://pasttenses.com/verbs-list/399',
        'https://pasttenses.com/verbs-list/400',
        'https://pasttenses.com/verbs-list/401',
        'https://pasttenses.com/verbs-list/402',
        'https://pasttenses.com/verbs-list/403',
        'https://pasttenses.com/verbs-list/404',
        'https://pasttenses.com/verbs-list/405',
        'https://pasttenses.com/verbs-list/406',
        'https://pasttenses.com/verbs-list/407',
        'https://pasttenses.com/verbs-list/408',
        'https://pasttenses.com/verbs-list/409',
        'https://pasttenses.com/verbs-list/410',
        'https://pasttenses.com/verbs-list/411',
        'https://pasttenses.com/verbs-list/412',
        'https://pasttenses.com/verbs-list/413',
        'https://pasttenses.com/verbs-list/414',
        'https://pasttenses.com/verbs-list/415',
        'https://pasttenses.com/verbs-list/416',
        'https://pasttenses.com/verbs-list/417',
        'https://pasttenses.com/verbs-list/418',
        'https://pasttenses.com/verbs-list/419',
        'https://pasttenses.com/verbs-list/420',
        'https://pasttenses.com/verbs-list/421',
        'https://pasttenses.com/verbs-list/422',
        'https://pasttenses.com/verbs-list/423',
        'https://pasttenses.com/verbs-list/424',
        'https://pasttenses.com/verbs-list/425',
        'https://pasttenses.com/verbs-list/426',
        'https://pasttenses.com/verbs-list/427',
        'https://pasttenses.com/verbs-list/428',
        'https://pasttenses.com/verbs-list/429',
        'https://pasttenses.com/verbs-list/430',
        'https://pasttenses.com/verbs-list/431',
        'https://pasttenses.com/verbs-list/432',
        'https://pasttenses.com/verbs-list/433',
        'https://pasttenses.com/verbs-list/434',
        'https://pasttenses.com/verbs-list/435',
        'https://pasttenses.com/verbs-list/436',
        'https://pasttenses.com/verbs-list/437',
        'https://pasttenses.com/verbs-list/438',
        'https://pasttenses.com/verbs-list/439',
        'https://pasttenses.com/verbs-list/440',
        'https://pasttenses.com/verbs-list/441',
        'https://pasttenses.com/verbs-list/442',
        'https://pasttenses.com/verbs-list/443',
        'https://pasttenses.com/verbs-list/444',
        'https://pasttenses.com/verbs-list/445',
        'https://pasttenses.com/verbs-list/446',
        'https://pasttenses.com/verbs-list/447',
        'https://pasttenses.com/verbs-list/448',
        'https://pasttenses.com/verbs-list/449',
        'https://pasttenses.com/verbs-list/450',
        'https://pasttenses.com/verbs-list/451',
        'https://pasttenses.com/verbs-list/452',
        'https://pasttenses.com/verbs-list/453',
        'https://pasttenses.com/verbs-list/454',
        'https://pasttenses.com/verbs-list/455',
        'https://pasttenses.com/verbs-list/456',
        'https://pasttenses.com/verbs-list/457',
        'https://pasttenses.com/verbs-list/458',
        'https://pasttenses.com/verbs-list/459',
        'https://pasttenses.com/verbs-list/460',
        'https://pasttenses.com/verbs-list/461',
        'https://pasttenses.com/verbs-list/462',
        'https://pasttenses.com/verbs-list/463',
        'https://pasttenses.com/verbs-list/464',
        'https://pasttenses.com/verbs-list/465',
        'https://pasttenses.com/verbs-list/466',
        'https://pasttenses.com/verbs-list/467',
        'https://pasttenses.com/verbs-list/468',
        'https://pasttenses.com/verbs-list/469',
        'https://pasttenses.com/verbs-list/470',
        'https://pasttenses.com/verbs-list/471',
        'https://pasttenses.com/verbs-list/472',
        'https://pasttenses.com/verbs-list/473',
        'https://pasttenses.com/verbs-list/474',
        'https://pasttenses.com/verbs-list/475',
        'https://pasttenses.com/verbs-list/476',
        'https://pasttenses.com/verbs-list/477',
        'https://pasttenses.com/verbs-list/478',
        'https://pasttenses.com/verbs-list/479',
        'https://pasttenses.com/verbs-list/480',
        'https://pasttenses.com/verbs-list/481',
        'https://pasttenses.com/verbs-list/482',
        'https://pasttenses.com/verbs-list/483',
        'https://pasttenses.com/verbs-list/484',
        'https://pasttenses.com/verbs-list/485',
        'https://pasttenses.com/verbs-list/486',
        'https://pasttenses.com/verbs-list/487',
        'https://pasttenses.com/verbs-list/488',
        'https://pasttenses.com/verbs-list/489',
        'https://pasttenses.com/verbs-list/490',
        'https://pasttenses.com/verbs-list/491',
        'https://pasttenses.com/verbs-list/492',
        'https://pasttenses.com/verbs-list/493',
        'https://pasttenses.com/verbs-list/494',
        'https://pasttenses.com/verbs-list/495',
        'https://pasttenses.com/verbs-list/496',
        'https://pasttenses.com/verbs-list/497',
        'https://pasttenses.com/verbs-list/498',
        'https://pasttenses.com/verbs-list/499',
        'https://pasttenses.com/verbs-list/500',
        'https://pasttenses.com/verbs-list/501',
        'https://pasttenses.com/verbs-list/502',
        'https://pasttenses.com/verbs-list/503',
        'https://pasttenses.com/verbs-list/504',
        'https://pasttenses.com/verbs-list/505',
        'https://pasttenses.com/verbs-list/506',
        'https://pasttenses.com/verbs-list/507',
        'https://pasttenses.com/verbs-list/508',
        'https://pasttenses.com/verbs-list/509',
        'https://pasttenses.com/verbs-list/510',
        'https://pasttenses.com/verbs-list/511',
        'https://pasttenses.com/verbs-list/512',
        'https://pasttenses.com/verbs-list/513',
        'https://pasttenses.com/verbs-list/514',
        'https://pasttenses.com/verbs-list/515',
        'https://pasttenses.com/verbs-list/516',
        'https://pasttenses.com/verbs-list/517',
        'https://pasttenses.com/verbs-list/518',
        'https://pasttenses.com/verbs-list/519',
        'https://pasttenses.com/verbs-list/520',
        'https://pasttenses.com/verbs-list/521',
        'https://pasttenses.com/verbs-list/522',
        'https://pasttenses.com/verbs-list/523',
        'https://pasttenses.com/verbs-list/524',
        'https://pasttenses.com/verbs-list/525',
        'https://pasttenses.com/verbs-list/526',
        'https://pasttenses.com/verbs-list/527',
        'https://pasttenses.com/verbs-list/528',
        'https://pasttenses.com/verbs-list/529',
        'https://pasttenses.com/verbs-list/530',
        'https://pasttenses.com/verbs-list/531',
        'https://pasttenses.com/verbs-list/532',
        'https://pasttenses.com/verbs-list/533',
        'https://pasttenses.com/verbs-list/534',
        'https://pasttenses.com/verbs-list/535',
        'https://pasttenses.com/verbs-list/536',
        'https://pasttenses.com/verbs-list/537',
        'https://pasttenses.com/verbs-list/538',
        'https://pasttenses.com/verbs-list/539',
        'https://pasttenses.com/verbs-list/540',
        'https://pasttenses.com/verbs-list/541',
        'https://pasttenses.com/verbs-list/542',
        'https://pasttenses.com/verbs-list/543',
        'https://pasttenses.com/verbs-list/544',
        'https://pasttenses.com/verbs-list/545',
        'https://pasttenses.com/verbs-list/546',
        'https://pasttenses.com/verbs-list/547',
        'https://pasttenses.com/verbs-list/548',
        'https://pasttenses.com/verbs-list/549',
        'https://pasttenses.com/verbs-list/550',
        'https://pasttenses.com/verbs-list/551',
        'https://pasttenses.com/verbs-list/552',
        'https://pasttenses.com/verbs-list/553',
        'https://pasttenses.com/verbs-list/554',
        'https://pasttenses.com/verbs-list/555',
        'https://pasttenses.com/verbs-list/556',
        'https://pasttenses.com/verbs-list/557',
        'https://pasttenses.com/verbs-list/558',
        'https://pasttenses.com/verbs-list/559',
        'https://pasttenses.com/verbs-list/560',
        'https://pasttenses.com/verbs-list/561',
        'https://pasttenses.com/verbs-list/562',
        'https://pasttenses.com/verbs-list/563',
        'https://pasttenses.com/verbs-list/564',
        'https://pasttenses.com/verbs-list/565',
        'https://pasttenses.com/verbs-list/566',
        'https://pasttenses.com/verbs-list/567',
        'https://pasttenses.com/verbs-list/568',
        'https://pasttenses.com/verbs-list/569',
        'https://pasttenses.com/verbs-list/570',
        'https://pasttenses.com/verbs-list/571',
        'https://pasttenses.com/verbs-list/572',
        'https://pasttenses.com/verbs-list/573',
        'https://pasttenses.com/verbs-list/574',
        'https://pasttenses.com/verbs-list/575',
        'https://pasttenses.com/verbs-list/576',
        'https://pasttenses.com/verbs-list/577',
        'https://pasttenses.com/verbs-list/578',
        'https://pasttenses.com/verbs-list/579',
        'https://pasttenses.com/verbs-list/580',
        'https://pasttenses.com/verbs-list/581',
        'https://pasttenses.com/verbs-list/582',
        'https://pasttenses.com/verbs-list/583',
        'https://pasttenses.com/verbs-list/584',
        'https://pasttenses.com/verbs-list/585',
        'https://pasttenses.com/verbs-list/586',
        'https://pasttenses.com/verbs-list/587',
        'https://pasttenses.com/verbs-list/588',
        'https://pasttenses.com/verbs-list/589',
        'https://pasttenses.com/verbs-list/590',
        'https://pasttenses.com/verbs-list/591',
        'https://pasttenses.com/verbs-list/592',
        'https://pasttenses.com/verbs-list/593',
        'https://pasttenses.com/verbs-list/594',
        'https://pasttenses.com/verbs-list/595',
        'https://pasttenses.com/verbs-list/596',
        'https://pasttenses.com/verbs-list/597',
        'https://pasttenses.com/verbs-list/598',
        'https://pasttenses.com/verbs-list/599',
        'https://pasttenses.com/verbs-list/600',
        'https://pasttenses.com/verbs-list/601',
        'https://pasttenses.com/verbs-list/602',
        'https://pasttenses.com/verbs-list/603',
        'https://pasttenses.com/verbs-list/604',
        'https://pasttenses.com/verbs-list/605',
        'https://pasttenses.com/verbs-list/606',
        'https://pasttenses.com/verbs-list/607',
        'https://pasttenses.com/verbs-list/608',
        'https://pasttenses.com/verbs-list/609',
        'https://pasttenses.com/verbs-list/610',
        'https://pasttenses.com/verbs-list/611',
        'https://pasttenses.com/verbs-list/612',
        'https://pasttenses.com/verbs-list/613',
        'https://pasttenses.com/verbs-list/614',
        'https://pasttenses.com/verbs-list/615',
        'https://pasttenses.com/verbs-list/616',
        'https://pasttenses.com/verbs-list/617',
        'https://pasttenses.com/verbs-list/618',
        'https://pasttenses.com/verbs-list/619',
        'https://pasttenses.com/verbs-list/620',
        'https://pasttenses.com/verbs-list/621',
        'https://pasttenses.com/verbs-list/622',
        'https://pasttenses.com/verbs-list/623',
        'https://pasttenses.com/verbs-list/624',
        'https://pasttenses.com/verbs-list/625',
        'https://pasttenses.com/verbs-list/626',
        'https://pasttenses.com/verbs-list/627',
        'https://pasttenses.com/verbs-list/628',
        'https://pasttenses.com/verbs-list/629',
        'https://pasttenses.com/verbs-list/630',
        'https://pasttenses.com/verbs-list/631',
        'https://pasttenses.com/verbs-list/632',
        'https://pasttenses.com/verbs-list/633',
        'https://pasttenses.com/verbs-list/634',
        'https://pasttenses.com/verbs-list/635',
        'https://pasttenses.com/verbs-list/636',
        'https://pasttenses.com/verbs-list/637',
        'https://pasttenses.com/verbs-list/638',
        'https://pasttenses.com/verbs-list/639',
        'https://pasttenses.com/verbs-list/640',
        'https://pasttenses.com/verbs-list/641',
        'https://pasttenses.com/verbs-list/642',
        'https://pasttenses.com/verbs-list/643',
        'https://pasttenses.com/verbs-list/644',
        'https://pasttenses.com/verbs-list/645',
        'https://pasttenses.com/verbs-list/646',
        'https://pasttenses.com/verbs-list/647',
        'https://pasttenses.com/verbs-list/648',
        'https://pasttenses.com/verbs-list/649',
        'https://pasttenses.com/verbs-list/650',
        'https://pasttenses.com/verbs-list/651',
        'https://pasttenses.com/verbs-list/652',
        'https://pasttenses.com/verbs-list/653',
        'https://pasttenses.com/verbs-list/654',
        'https://pasttenses.com/verbs-list/655',
        'https://pasttenses.com/verbs-list/656',
        'https://pasttenses.com/verbs-list/657',
        'https://pasttenses.com/verbs-list/658',
        'https://pasttenses.com/verbs-list/659',
        'https://pasttenses.com/verbs-list/660',
        'https://pasttenses.com/verbs-list/661',
        'https://pasttenses.com/verbs-list/662',
        'https://pasttenses.com/verbs-list/663',
        'https://pasttenses.com/verbs-list/664',
        'https://pasttenses.com/verbs-list/665',
        'https://pasttenses.com/verbs-list/666',
        'https://pasttenses.com/verbs-list/667',
        'https://pasttenses.com/verbs-list/668',
        'https://pasttenses.com/verbs-list/669',
        'https://pasttenses.com/verbs-list/670',
        'https://pasttenses.com/verbs-list/671',
        'https://pasttenses.com/verbs-list/672',
        'https://pasttenses.com/verbs-list/673',
        'https://pasttenses.com/verbs-list/674',
        'https://pasttenses.com/verbs-list/675',
        'https://pasttenses.com/verbs-list/676',
        'https://pasttenses.com/verbs-list/677',
        'https://pasttenses.com/verbs-list/678',
        'https://pasttenses.com/verbs-list/679',
        'https://pasttenses.com/verbs-list/680',
        'https://pasttenses.com/verbs-list/681',
        'https://pasttenses.com/verbs-list/682',
        'https://pasttenses.com/verbs-list/683',
        'https://pasttenses.com/verbs-list/684',
        'https://pasttenses.com/verbs-list/685',
        'https://pasttenses.com/verbs-list/686',
        'https://pasttenses.com/verbs-list/687',
        'https://pasttenses.com/verbs-list/688',
        'https://pasttenses.com/verbs-list/689',
        'https://pasttenses.com/verbs-list/690',
        'https://pasttenses.com/verbs-list/691',
        'https://pasttenses.com/verbs-list/692',
        'https://pasttenses.com/verbs-list/693',
        'https://pasttenses.com/verbs-list/694',
        'https://pasttenses.com/verbs-list/695',
        'https://pasttenses.com/verbs-list/696',
        'https://pasttenses.com/verbs-list/697',
        'https://pasttenses.com/verbs-list/698',
        'https://pasttenses.com/verbs-list/699',
        'https://pasttenses.com/verbs-list/700',
        'https://pasttenses.com/verbs-list/701',
        'https://pasttenses.com/verbs-list/702',
        'https://pasttenses.com/verbs-list/703',
        'https://pasttenses.com/verbs-list/704',
        'https://pasttenses.com/verbs-list/705',
        'https://pasttenses.com/verbs-list/706',
        'https://pasttenses.com/verbs-list/707',
        'https://pasttenses.com/verbs-list/708',
        'https://pasttenses.com/verbs-list/709',
        'https://pasttenses.com/verbs-list/710',
        'https://pasttenses.com/verbs-list/711',
        'https://pasttenses.com/verbs-list/712',
        'https://pasttenses.com/verbs-list/713',
        'https://pasttenses.com/verbs-list/714',
        'https://pasttenses.com/verbs-list/715',
        'https://pasttenses.com/verbs-list/716',
        'https://pasttenses.com/verbs-list/717',
        'https://pasttenses.com/verbs-list/718',
        'https://pasttenses.com/verbs-list/719',
        'https://pasttenses.com/verbs-list/720',
        'https://pasttenses.com/verbs-list/721',
        'https://pasttenses.com/verbs-list/722',
        'https://pasttenses.com/verbs-list/723',
        'https://pasttenses.com/verbs-list/724',
        'https://pasttenses.com/verbs-list/725',
        'https://pasttenses.com/verbs-list/726',
        'https://pasttenses.com/verbs-list/727',
        'https://pasttenses.com/verbs-list/728',
        'https://pasttenses.com/verbs-list/729',
        'https://pasttenses.com/verbs-list/730',
        'https://pasttenses.com/verbs-list/731',
        'https://pasttenses.com/verbs-list/732',
        'https://pasttenses.com/verbs-list/733',
        'https://pasttenses.com/verbs-list/734',
        'https://pasttenses.com/verbs-list/735',
        'https://pasttenses.com/verbs-list/736',
        'https://pasttenses.com/verbs-list/737',
        'https://pasttenses.com/verbs-list/738',
        'https://pasttenses.com/verbs-list/739',
        'https://pasttenses.com/verbs-list/740',
        'https://pasttenses.com/verbs-list/741',
        'https://pasttenses.com/verbs-list/742',
        'https://pasttenses.com/verbs-list/743',
        'https://pasttenses.com/verbs-list/744',
        'https://pasttenses.com/verbs-list/745',
        'https://pasttenses.com/verbs-list/746',
        'https://pasttenses.com/verbs-list/747',
        'https://pasttenses.com/verbs-list/748',
        'https://pasttenses.com/verbs-list/749',
        'https://pasttenses.com/verbs-list/750',
        'https://pasttenses.com/verbs-list/751',
        'https://pasttenses.com/verbs-list/752',
        'https://pasttenses.com/verbs-list/753',
        'https://pasttenses.com/verbs-list/754',
        'https://pasttenses.com/verbs-list/755',
        'https://pasttenses.com/verbs-list/756',
        'https://pasttenses.com/verbs-list/757',
        'https://pasttenses.com/verbs-list/758',
        'https://pasttenses.com/verbs-list/759',
        'https://pasttenses.com/verbs-list/760',
        'https://pasttenses.com/verbs-list/761',
        'https://pasttenses.com/verbs-list/762',
        'https://pasttenses.com/verbs-list/763',
        'https://pasttenses.com/verbs-list/764',
        'https://pasttenses.com/verbs-list/765',
        'https://pasttenses.com/verbs-list/766',
        'https://pasttenses.com/verbs-list/767',
        'https://pasttenses.com/verbs-list/768',
        'https://pasttenses.com/verbs-list/769',
        'https://pasttenses.com/verbs-list/770',
        'https://pasttenses.com/verbs-list/771',
        'https://pasttenses.com/verbs-list/772',
        'https://pasttenses.com/verbs-list/773',
        'https://pasttenses.com/verbs-list/774',
        'https://pasttenses.com/verbs-list/775',
        'https://pasttenses.com/verbs-list/776',
        'https://pasttenses.com/verbs-list/777',
        'https://pasttenses.com/verbs-list/778',
        'https://pasttenses.com/verbs-list/779',
        'https://pasttenses.com/verbs-list/780',
        'https://pasttenses.com/verbs-list/781',
        'https://pasttenses.com/verbs-list/782',
        'https://pasttenses.com/verbs-list/783',
        'https://pasttenses.com/verbs-list/784',
        'https://pasttenses.com/verbs-list/785',
        'https://pasttenses.com/verbs-list/786',
        'https://pasttenses.com/verbs-list/787',
        'https://pasttenses.com/verbs-list/788',
        'https://pasttenses.com/verbs-list/789',
        'https://pasttenses.com/verbs-list/790',
        'https://pasttenses.com/verbs-list/791',
        'https://pasttenses.com/verbs-list/792',
        'https://pasttenses.com/verbs-list/793',
        'https://pasttenses.com/verbs-list/794',
        'https://pasttenses.com/verbs-list/795',
        'https://pasttenses.com/verbs-list/796',
        'https://pasttenses.com/verbs-list/797',
        'https://pasttenses.com/verbs-list/798',
        'https://pasttenses.com/verbs-list/799',
        'https://pasttenses.com/verbs-list/800',
        'https://pasttenses.com/verbs-list/801',
        'https://pasttenses.com/verbs-list/802',
        'https://pasttenses.com/verbs-list/803',
        'https://pasttenses.com/verbs-list/804',
        'https://pasttenses.com/verbs-list/805',
        'https://pasttenses.com/verbs-list/806',
        'https://pasttenses.com/verbs-list/807',
        'https://pasttenses.com/verbs-list/808',
        'https://pasttenses.com/verbs-list/809',
        'https://pasttenses.com/verbs-list/810',
        'https://pasttenses.com/verbs-list/811',
        'https://pasttenses.com/verbs-list/812',
        'https://pasttenses.com/verbs-list/813',
        'https://pasttenses.com/verbs-list/814',
        'https://pasttenses.com/verbs-list/815',
        'https://pasttenses.com/verbs-list/816',
        'https://pasttenses.com/verbs-list/817',
        'https://pasttenses.com/verbs-list/818',
        'https://pasttenses.com/verbs-list/819',
        'https://pasttenses.com/verbs-list/820',
        'https://pasttenses.com/verbs-list/821',
        'https://pasttenses.com/verbs-list/822',
        'https://pasttenses.com/verbs-list/823',
        'https://pasttenses.com/verbs-list/824',
        'https://pasttenses.com/verbs-list/825',
        'https://pasttenses.com/verbs-list/826',
        'https://pasttenses.com/verbs-list/827',
        'https://pasttenses.com/verbs-list/828',
        'https://pasttenses.com/verbs-list/829',
        'https://pasttenses.com/verbs-list/830',
        'https://pasttenses.com/verbs-list/831',
        'https://pasttenses.com/verbs-list/832',
        'https://pasttenses.com/verbs-list/833',
        'https://pasttenses.com/verbs-list/834',
        'https://pasttenses.com/verbs-list/835',
        'https://pasttenses.com/verbs-list/836',
        'https://pasttenses.com/verbs-list/837',
        'https://pasttenses.com/verbs-list/838',
        'https://pasttenses.com/verbs-list/839',
        'https://pasttenses.com/verbs-list/840',
        'https://pasttenses.com/verbs-list/841',
        'https://pasttenses.com/verbs-list/842',
        'https://pasttenses.com/verbs-list/843',
        'https://pasttenses.com/verbs-list/844',
        'https://pasttenses.com/verbs-list/845',
        'https://pasttenses.com/verbs-list/846',
        'https://pasttenses.com/verbs-list/847',
        'https://pasttenses.com/verbs-list/848',
        'https://pasttenses.com/verbs-list/849',
        'https://pasttenses.com/verbs-list/850',
        'https://pasttenses.com/verbs-list/851',
        'https://pasttenses.com/verbs-list/852',
        'https://pasttenses.com/verbs-list/853',
        'https://pasttenses.com/verbs-list/854',
        'https://pasttenses.com/verbs-list/855',
        'https://pasttenses.com/verbs-list/856',
        'https://pasttenses.com/verbs-list/857',
        'https://pasttenses.com/verbs-list/858',
        'https://pasttenses.com/verbs-list/859',
        'https://pasttenses.com/verbs-list/860',
        'https://pasttenses.com/verbs-list/861',
        'https://pasttenses.com/verbs-list/862',
        'https://pasttenses.com/verbs-list/863',
        'https://pasttenses.com/verbs-list/864',
        'https://pasttenses.com/verbs-list/865',
        'https://pasttenses.com/verbs-list/866',
        'https://pasttenses.com/verbs-list/867',
        'https://pasttenses.com/verbs-list/868',
        'https://pasttenses.com/verbs-list/869',
        'https://pasttenses.com/verbs-list/870',
        'https://pasttenses.com/verbs-list/871',
        'https://pasttenses.com/verbs-list/872',
        'https://pasttenses.com/verbs-list/873',
        'https://pasttenses.com/verbs-list/874',
        'https://pasttenses.com/verbs-list/875',
        'https://pasttenses.com/verbs-list/876',
        'https://pasttenses.com/verbs-list/877',
        'https://pasttenses.com/verbs-list/878',
        'https://pasttenses.com/verbs-list/879',
        'https://pasttenses.com/verbs-list/880',
        'https://pasttenses.com/verbs-list/881',
        'https://pasttenses.com/verbs-list/882',
        'https://pasttenses.com/verbs-list/883',
        'https://pasttenses.com/verbs-list/884',
        'https://pasttenses.com/verbs-list/885',
        'https://pasttenses.com/verbs-list/886',
        'https://pasttenses.com/verbs-list/887',
        'https://pasttenses.com/verbs-list/888',
        'https://pasttenses.com/verbs-list/889',
        'https://pasttenses.com/verbs-list/890',
        'https://pasttenses.com/verbs-list/891',
        'https://pasttenses.com/verbs-list/892',
        'https://pasttenses.com/verbs-list/893',
        'https://pasttenses.com/verbs-list/894',
        'https://pasttenses.com/verbs-list/895',
        'https://pasttenses.com/verbs-list/896',
        'https://pasttenses.com/verbs-list/897',
        'https://pasttenses.com/verbs-list/898',
        'https://pasttenses.com/verbs-list/899',
        'https://pasttenses.com/verbs-list/900',
        'https://pasttenses.com/verbs-list/901',
        'https://pasttenses.com/verbs-list/902',
        'https://pasttenses.com/verbs-list/903',
        'https://pasttenses.com/verbs-list/904',
        'https://pasttenses.com/verbs-list/905',
        'https://pasttenses.com/verbs-list/906',
        'https://pasttenses.com/verbs-list/907',
        'https://pasttenses.com/verbs-list/908',
        'https://pasttenses.com/verbs-list/909',
        'https://pasttenses.com/verbs-list/910',
        'https://pasttenses.com/verbs-list/911',
        'https://pasttenses.com/verbs-list/912',
        'https://pasttenses.com/verbs-list/913',
        'https://pasttenses.com/verbs-list/914',
        'https://pasttenses.com/verbs-list/915',
        'https://pasttenses.com/verbs-list/916',
        'https://pasttenses.com/verbs-list/917',
        'https://pasttenses.com/verbs-list/918',
        'https://pasttenses.com/verbs-list/919',
        'https://pasttenses.com/verbs-list/920',
        'https://pasttenses.com/verbs-list/921',
        'https://pasttenses.com/verbs-list/922',
        'https://pasttenses.com/verbs-list/923',
        'https://pasttenses.com/verbs-list/924',
        'https://pasttenses.com/verbs-list/925',
        'https://pasttenses.com/verbs-list/926',
        'https://pasttenses.com/verbs-list/927',
        'https://pasttenses.com/verbs-list/928',
        'https://pasttenses.com/verbs-list/929',
        'https://pasttenses.com/verbs-list/930',
        'https://pasttenses.com/verbs-list/931',
        'https://pasttenses.com/verbs-list/932',
        'https://pasttenses.com/verbs-list/933',
        'https://pasttenses.com/verbs-list/934',
        'https://pasttenses.com/verbs-list/935',
        'https://pasttenses.com/verbs-list/936',
        'https://pasttenses.com/verbs-list/937',
        'https://pasttenses.com/verbs-list/938',
        'https://pasttenses.com/verbs-list/939',
        'https://pasttenses.com/verbs-list/940',
        'https://pasttenses.com/verbs-list/941',
        'https://pasttenses.com/verbs-list/942',
        'https://pasttenses.com/verbs-list/943',
        'https://pasttenses.com/verbs-list/944',
        'https://pasttenses.com/verbs-list/945',
        'https://pasttenses.com/verbs-list/946',
        'https://pasttenses.com/verbs-list/947',
        'https://pasttenses.com/verbs-list/948',
        'https://pasttenses.com/verbs-list/949',
        'https://pasttenses.com/verbs-list/950',
        'https://pasttenses.com/verbs-list/951',
        'https://pasttenses.com/verbs-list/952',
        'https://pasttenses.com/verbs-list/953',
        'https://pasttenses.com/verbs-list/954',
        'https://pasttenses.com/verbs-list/955',
        'https://pasttenses.com/verbs-list/956',
        'https://pasttenses.com/verbs-list/957',
        'https://pasttenses.com/verbs-list/958',
        'https://pasttenses.com/verbs-list/959',
        'https://pasttenses.com/verbs-list/960',
        'https://pasttenses.com/verbs-list/961',
        'https://pasttenses.com/verbs-list/962',
        'https://pasttenses.com/verbs-list/963',
        'https://pasttenses.com/verbs-list/964',
        'https://pasttenses.com/verbs-list/965',
        'https://pasttenses.com/verbs-list/966',
        'https://pasttenses.com/verbs-list/967',
        'https://pasttenses.com/verbs-list/968',
        'https://pasttenses.com/verbs-list/969',
        'https://pasttenses.com/verbs-list/970',
        'https://pasttenses.com/verbs-list/971',
        'https://pasttenses.com/verbs-list/972',
        'https://pasttenses.com/verbs-list/973',
        'https://pasttenses.com/verbs-list/974',
        'https://pasttenses.com/verbs-list/975',
        'https://pasttenses.com/verbs-list/976',
        'https://pasttenses.com/verbs-list/977',
        'https://pasttenses.com/verbs-list/978',
        'https://pasttenses.com/verbs-list/979',
        'https://pasttenses.com/verbs-list/980',
        'https://pasttenses.com/verbs-list/981',
        'https://pasttenses.com/verbs-list/982',
        'https://pasttenses.com/verbs-list/983',
        'https://pasttenses.com/verbs-list/984',
        'https://pasttenses.com/verbs-list/985',
        'https://pasttenses.com/verbs-list/986',
        'https://pasttenses.com/verbs-list/987',
        'https://pasttenses.com/verbs-list/988',
        'https://pasttenses.com/verbs-list/989',
        'https://pasttenses.com/verbs-list/990',
        'https://pasttenses.com/verbs-list/991',
        'https://pasttenses.com/verbs-list/992',
        'https://pasttenses.com/verbs-list/993',
        'https://pasttenses.com/verbs-list/994',
        'https://pasttenses.com/verbs-list/995',
        'https://pasttenses.com/verbs-list/996',
        'https://pasttenses.com/verbs-list/997',
        'https://pasttenses.com/verbs-list/998',
        'https://pasttenses.com/verbs-list/999',
        'https://pasttenses.com/verbs-list/1000',
        'https://pasttenses.com/verbs-list/1001',
        'https://pasttenses.com/verbs-list/1002',
        'https://pasttenses.com/verbs-list/1003',
        'https://pasttenses.com/verbs-list/1004',
        'https://pasttenses.com/verbs-list/1005',
        'https://pasttenses.com/verbs-list/1006',
        'https://pasttenses.com/verbs-list/1007',
        'https://pasttenses.com/verbs-list/1008',
        'https://pasttenses.com/verbs-list/1009',
        'https://pasttenses.com/verbs-list/1010',
        'https://pasttenses.com/verbs-list/1011',
        'https://pasttenses.com/verbs-list/1012',
        'https://pasttenses.com/verbs-list/1013',
        'https://pasttenses.com/verbs-list/1014',
        'https://pasttenses.com/verbs-list/1015',
        'https://pasttenses.com/verbs-list/1016',
        'https://pasttenses.com/verbs-list/1017',
        'https://pasttenses.com/verbs-list/1018',
        'https://pasttenses.com/verbs-list/1019',
        'https://pasttenses.com/verbs-list/1020',
        'https://pasttenses.com/verbs-list/1021',
        'https://pasttenses.com/verbs-list/1022',
        'https://pasttenses.com/verbs-list/1023',
        'https://pasttenses.com/verbs-list/1024',
        'https://pasttenses.com/verbs-list/1025',
        'https://pasttenses.com/verbs-list/1026',
        'https://pasttenses.com/verbs-list/1027',
        'https://pasttenses.com/verbs-list/1028',
        'https://pasttenses.com/verbs-list/1029',
        'https://pasttenses.com/verbs-list/1030',
        'https://pasttenses.com/verbs-list/1031',
        'https://pasttenses.com/verbs-list/1032',
        'https://pasttenses.com/verbs-list/1033',
        'https://pasttenses.com/verbs-list/1034',
        'https://pasttenses.com/verbs-list/1035',
        'https://pasttenses.com/verbs-list/1036',
        'https://pasttenses.com/verbs-list/1037',
        'https://pasttenses.com/verbs-list/1038',
        'https://pasttenses.com/verbs-list/1039',
        'https://pasttenses.com/verbs-list/1040',
        'https://pasttenses.com/verbs-list/1041',
        'https://pasttenses.com/verbs-list/1042',
        'https://pasttenses.com/verbs-list/1043',
        'https://pasttenses.com/verbs-list/1044',
        'https://pasttenses.com/verbs-list/1045',
        'https://pasttenses.com/verbs-list/1046',
        'https://pasttenses.com/verbs-list/1047',
        'https://pasttenses.com/verbs-list/1048',
        'https://pasttenses.com/verbs-list/1049',
        'https://pasttenses.com/verbs-list/1050',
        'https://pasttenses.com/verbs-list/1051',
        'https://pasttenses.com/verbs-list/1052',
        'https://pasttenses.com/verbs-list/1053',
        'https://pasttenses.com/verbs-list/1054',
        'https://pasttenses.com/verbs-list/1055',
        'https://pasttenses.com/verbs-list/1056',
        'https://pasttenses.com/verbs-list/1057',
        'https://pasttenses.com/verbs-list/1058',
        'https://pasttenses.com/verbs-list/1059',
        'https://pasttenses.com/verbs-list/1060',
        'https://pasttenses.com/verbs-list/1061',
        'https://pasttenses.com/verbs-list/1062',
        'https://pasttenses.com/verbs-list/1063',
        'https://pasttenses.com/verbs-list/1064',
        'https://pasttenses.com/verbs-list/1065',
        'https://pasttenses.com/verbs-list/1066',
        'https://pasttenses.com/verbs-list/1067',
        'https://pasttenses.com/verbs-list/1068',
        'https://pasttenses.com/verbs-list/1069',
        'https://pasttenses.com/verbs-list/1070',
        'https://pasttenses.com/verbs-list/1071',
        'https://pasttenses.com/verbs-list/1072',
        'https://pasttenses.com/verbs-list/1073',
        'https://pasttenses.com/verbs-list/1074',
        'https://pasttenses.com/verbs-list/1075',
        'https://pasttenses.com/verbs-list/1076',
        'https://pasttenses.com/verbs-list/1077',
        'https://pasttenses.com/verbs-list/1078',
        'https://pasttenses.com/verbs-list/1079',
        'https://pasttenses.com/verbs-list/1080',
        'https://pasttenses.com/verbs-list/1081',
        'https://pasttenses.com/verbs-list/1082',
        'https://pasttenses.com/verbs-list/1083',
        'https://pasttenses.com/verbs-list/1084',
        'https://pasttenses.com/verbs-list/1085',
        'https://pasttenses.com/verbs-list/1086',
        'https://pasttenses.com/verbs-list/1087',
        'https://pasttenses.com/verbs-list/1088',
        'https://pasttenses.com/verbs-list/1089',
        'https://pasttenses.com/irregular-verbs-list/1',
        'https://pasttenses.com/irregular-verbs-list/2',
        'https://pasttenses.com/irregular-verbs-list/3',
        'https://pasttenses.com/irregular-verbs-list/4',
        'https://pasttenses.com/irregular-verbs-list/5',
        'https://pasttenses.com/irregular-verbs-list/6',
        'https://pasttenses.com/irregular-verbs-list/7',
        'https://pasttenses.com/irregular-verbs-list/8',
        'https://pasttenses.com/irregular-verbs-list/9',
        'https://pasttenses.com/irregular-verbs-list/10',
        'https://pasttenses.com/irregular-verbs-list/11',
        'https://pasttenses.com/irregular-verbs-list/12',
        'https://pasttenses.com/irregular-verbs-list/13',
        'https://pasttenses.com/irregular-verbs-list/14',
        'https://pasttenses.com/irregular-verbs-list/15',
        'https://pasttenses.com/irregular-verbs-list/16',
        'https://pasttenses.com/irregular-verbs-list/17',
        'https://pasttenses.com/irregular-verbs-list/18',
        'https://pasttenses.com/irregular-verbs-list/19',
        'https://pasttenses.com/irregular-verbs-list/20',
        'https://pasttenses.com/irregular-verbs-list/21',
        'https://pasttenses.com/irregular-verbs-list/22',
        'https://pasttenses.com/irregular-verbs-list/23',
        'https://pasttenses.com/irregular-verbs-list/24',
        'https://pasttenses.com/irregular-verbs-list/25',
        'https://pasttenses.com/irregular-verbs-list/26',
        'https://pasttenses.com/irregular-verbs-list/27',
        'https://pasttenses.com/irregular-verbs-list/28',
        'https://pasttenses.com/irregular-verbs-list/29',
        'https://pasttenses.com/irregular-verbs-list/30',
        'https://pasttenses.com/irregular-verbs-list/31'
    ]
    custom_settings = {
        'FEEDS':{
        'words.json':{
        'format':'json',
        'encoding':'utf8',
        }
        },
    }
    
    def parse_link (self, response, **kwargs):
        link = kwargs['link']
        verb = response.xpath('//div[@class="card border-light mb-3"]/h1[@class="card-header special1 heading"]/span/text()').get()
        verb = verb.split(' ', 1)[0]
        past = response.xpath('//div[@class="card border-light mb-3"]/div[@class="card-body"]/div[@class="card-text special"]/div[@class="content"]/span/text()').get()
        infinitive = response.xpath('//table[@class="table table-striped table-bordered tg"]//tr[2]/td[1]//text()').get()
        presentParticiple = response.xpath('//table[@class="table table-striped table-bordered tg"]//tr[2]/td[2]//text()').get()
        pastTense = response.xpath('//table[@class="table table-striped table-bordered tg"]//tr[2]/td[3]//text()').get()
        pastParticiple = response.xpath('//table[@class="table table-striped table-bordered tg"]//tr[2]/td[4]//text()').get()
        simplePresentConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[1]//tr[2]//text()').getall()
        simplePresentConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[1]//tr[3]//text()').getall()
        simplePresentConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[1]//tr[4]//text()').getall()
        presentContinuousConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[2]//tr[2]//text()').getall()
        presentContinuousConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[2]//tr[3]//text()').getall()
        presentContinuousConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[2]//tr[4]//text()').getall()
        presentPerfectConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[3]//tr[2]//text()').getall()
        presentPerfectConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[3]//tr[3]//text()').getall()
        presentPerfectConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[3]//tr[4]//text()').getall()
        presentPerfectContinuousConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[4]//tr[2]//text()').getall()
        presentPerfectContinuousConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[4]//tr[3]//text()').getall()
        presentPerfectContinuousConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[4]//tr[4]//text()').getall()
        simplePastConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[5]//tr[2]//text()').getall()
        simplePastConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[5]//tr[3]//text()').getall()
        simplePastConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[5]//tr[4]//text()').getall()
        pastContinuousConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[6]//tr[2]//text()').getall()
        pastContinuousConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[6]//tr[3]//text()').getall()
        pastContinuousConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[6]//tr[4]//text()').getall()
        pastPerfectConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[7]//tr[2]//text()').getall()
        pastPerfectConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[7]//tr[3]//text()').getall()
        pastPerfectConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[7]//tr[4]//text()').getall()
        pastPerfectContinuousConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[8]//tr[2]//text()').getall()
        pastPerfectContinuousConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[8]//tr[3]//text()').getall()
        pastPerfectContinuousConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[8]//tr[4]//text()').getall()
        futureConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[9]//tr[2]//text()').getall()
        futureConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[9]//tr[3]//text()').getall()
        futureConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[9]//tr[4]//text()').getall()
        futureContinuousConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[10]//tr[2]//text()').getall()
        futureContinuousConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[10]//tr[3]//text()').getall()
        futureContinuousConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[10]//tr[4]//text()').getall()
        futurePerfectConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[11]//tr[2]//text()').getall()
        futurePerfectConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[11]//tr[3]//text()').getall()
        futurePerfectConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[11]//tr[4]//text()').getall()
        futurePerfectContinuousConjugation1 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[12]//tr[2]//text()').getall()
        futurePerfectContinuousConjugation2 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[12]//tr[3]//text()').getall()
        futurePerfectContinuousConjugation3 = response.xpath('(//table[@class="table table-striped table-bordered table-light tg"])[12]//tr[4]//text()').getall()

        
        if past:
            return{
                'verb': verb,
                'past': past,
                'infinitive': infinitive,
                'presentParticiple': presentParticiple,
                'pastTense': pastTense,
                'pastParticiple': pastParticiple,
                "conjugationSimplePresent" : [ simplePresentConjugation1, simplePresentConjugation2, simplePresentConjugation3],
                "conjugationPresentContinuous" : [ presentContinuousConjugation1, presentContinuousConjugation2, presentContinuousConjugation3],
                "conjugationPresentPerfect" : [ presentPerfectConjugation1, presentPerfectConjugation2, presentPerfectConjugation3],
                "conjugationPresentPerfectContinuous" : [ presentPerfectContinuousConjugation1, presentPerfectContinuousConjugation2, presentPerfectContinuousConjugation3],
                "conjugationSimplePast" : [ simplePastConjugation1, simplePastConjugation2, simplePastConjugation3],
                "conjugationPastContinuous" : [ pastContinuousConjugation1, pastContinuousConjugation2, pastContinuousConjugation3],
                "conjugationPastPerfect" : [ pastPerfectConjugation1, pastPerfectConjugation2, pastPerfectConjugation3],
                "conjugationPastPerfectContinuous" : [ pastPerfectContinuousConjugation1, pastPerfectContinuousConjugation2, pastPerfectContinuousConjugation3],
                "conjugationFuture" : [ futureConjugation1, futureConjugation2, futureConjugation3],
                "conjugationFutureContinuous" : [ futureContinuousConjugation1, futureContinuousConjugation2, futureContinuousConjugation3],
                "conjugationFuturePerfect" : [ futurePerfectConjugation1, futurePerfectConjugation2, futurePerfectConjugation3],
                "conjugationFuturePerfectContinuous" : [ futurePerfectContinuousConjugation1, futurePerfectContinuousConjugation2, futurePerfectContinuousConjugation3],
            }
        else:
            return
        

    def parse (self, response):
        links = response.xpath('//td//a/@href').getall()
        for link in links: 
            yield response.follow(link, callback=self.parse_link, cb_kwargs = {'link': str(link)})